// app/components/easter-egg/senpai.tsx
import { ComponentChildren } from "preact";

import shout from "~/assets/audio/senpai.aac";
import poop from "~/assets/images/poop.webp";

export type SenpaiProps = {
  children?: ComponentChildren;
};

export function Senpai(props: SenpaiProps) {
  const shoutOut = () => {
    const audio = new Audio(shout);
    audio.addEventListener("canplay", () => {
      audio.play();
    });
  };

  return (
    <p>
      <span
        className="cursor-not-allowed"
        onClick={shoutOut}
        style={{
          cursor: `url(${poop}) 12 12, pointer`,
        }}
      >
        {props.children}
      </span>
    </p>
  );
}

// src/components/easter-egg/Senpai.vue
<template>
  <p>
    <span
      class="cursor-not-allowed"
      @click="shoutOut"
      :style="{ cursor: `url(${poop}) 12 12, pointer` }"
    >
      <slot />
    </span>
  </p>
</template>

<script setup lang="ts">
import shout from "@/assets/audio/senpai.aac";
import poop from "@/assets/images/poop.webp";

function shoutOut() {
  const audio = new Audio(shout);
  audio.addEventListener("canplay", () => {
    audio.play();
  });
}
</script>
