// src/components/typography/typography.tsx
import { ComponentChildren } from "preact";
import { Nav, NavPortal } from "../nav/nav.tsx";
import { Link } from "@biliblitz/blitz";
import { MDXProvider } from "@mdx-js/preact";

export const Typography = (props: { children?: ComponentChildren }) => {
  return (
    <div class="relative">
      <MDXProvider components={{ a: Link, "set-nav": NavPortal }}>
        <article class="typography">{props.children}</article>
      </MDXProvider>
    </div>
  );
};

// src/components/typography/Typography.vue
<template>
  <div class="relative">
    <article class="typography">
      <MDXProvider
        :components="{
          a: Link,
          'set-nav': NavPortal,
        }"
      >
        <slot />
      </MDXProvider>
    </article>
  </div>
</template>

<script setup lang="ts">
import { MDXProvider } from "@mdx-js/vue";
import Link from "./Link.vue";
import NavPortal from "../nav/NavPortal.vue";
</script>
